In [1]:
import pandas as pd
import numpy as np
import kagglehub

C:\Users\vipul\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import os
import warnings
warnings.filterwarnings("ignore")

In [3]:
# import kagglehub
# # Download latest version
# path = kagglehub.dataset_download("sohaibdevv/consumer-shopping-behavior-and-preference-study-2026")
# print("Path to dataset files:", path)

In [4]:
# import kagglehub
# # Download latest version
# path = kagglehub.dataset_download("sehaj1104/indian-road-accident-dataset-20222025")
# print("Path to dataset files:", path)

In [5]:
# import kagglehub
# # Download latest version
# path = kagglehub.dataset_download("sehaj1104/indian-road-accident-dataset-20222025")
# print("Path to dataset files:", path)

In [6]:
# path = kagglehub.dataset_download("sohaibdevv/consumer-shopping-behavior-and-preference-study-2026")

In [7]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("alitaqishah/tech-layoffs-2026-ai-job-cuts-tracker")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\vipul\.cache\kagglehub\datasets\alitaqishah\tech-layoffs-2026-ai-job-cuts-tracker\versions\1

In [8]:
for files in os.listdir(path):
    print(files)

tech_layoffs_2026_tracker.csv

In [9]:
file_path = path + "/tech_layoffs_2026.csv"
print("Full path to CSV file:", file_path)

Full path to CSV file: C:\Users\vipul\.cache\kagglehub\datasets\alitaqishah\tech-layoffs-2026-ai-job-cuts-tracker\versions\1/tech_layoffs_2026.csv

In [10]:
df = pd.read_csv(path + "/tech_layoffs_2026_tracker.csv")

In [11]:
df.head()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"

# loc:-
- In pandas, loc is a property used to access and manipulate data in a DataFrame or Series based on labels (names of rows and columns) rather than integer positions.

## Key Features
- Label-Based: You use actual row and column names (e.g., 'Alice', 'City') to retrieve data.
- Inclusive Slicing: Unlike standard Python slicing, loc includes both the start and end labels (e.g., df.loc['A':'C'] includes row 'C').
- Boolean Support: It can filter rows based on conditions (e.g., df.loc[df['Age'] > 30]).
- Updating Data: It is the preferred method for modifying specific values in a DataFrame to avoid "Chained Assignment" warnings.

## Basic Syntax
- The standard format for the pandas.DataFrame.loc property is:
df.loc[row_label, column_label]

## Usage Examples
- Single Value: df.loc['row1', 'col1'] returns the value at that specific intersection.
- Full Row: df.loc['row1'] or df.loc['row1', :] returns all columns for a specific row.
- Multiple Rows/Columns: df.loc[['A', 'B'], ['Name', 'Age']] uses lists to select specific subsets.
- Slicing: df.loc['row1':'row5', 'colA':'colC'] selects a range of data inclusive of endpoints.
- Filtering: df.loc[df['Salary'] > 50000] returns rows where the condition is met

In [12]:
df.head()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"

In [13]:
# by single value row and column name
df.loc[0, "company"]

'Amazon'

In [14]:
# Full Row:
df.loc[7]

company                                                            eBay
layoff_date                                                  2026-01-28
jobs_cut                                                            800
pct_workforce_cut                                                   5.0
sector                                                       E-Commerce
country                                                             USA
hq_city                                                        San Jose
ai_cited                                                           True
reason_stated                       AI-forward strategy in customer ops
company_revenue_2025_bn                                            10.3
pre_layoff_headcount                                              11000
stock_change_day_pct                                                1.2
simultaneous_ai_investment_bn                                       0.8
roles_most_affected                Content moderation, customer support
replacement_roles                                  AI content reviewers
ceo_quote                        AI handles majority of support tickets
layoffs_2024                                                       1000
layoffs_2025                                                       1000
verified_source                                            NetworkWorld
month                                                      January 2026
quarter                                                         Q1 2026
region                                                    North America
layoff_size_category                                    Medium (500-2K)
stock_reaction                                                 Positive
laid_off_vs_headcount_pct                                          7.27
data_as_of                                               March 18, 2026
Name: 7, dtype: object

In [15]:
df.loc[7,:]

company                                                            eBay
layoff_date                                                  2026-01-28
jobs_cut                                                            800
pct_workforce_cut                                                   5.0
sector                                                       E-Commerce
country                                                             USA
hq_city                                                        San Jose
ai_cited                                                           True
reason_stated                       AI-forward strategy in customer ops
company_revenue_2025_bn                                            10.3
pre_layoff_headcount                                              11000
stock_change_day_pct                                                1.2
simultaneous_ai_investment_bn                                       0.8
roles_most_affected                Content moderation, customer support
replacement_roles                                  AI content reviewers
ceo_quote                        AI handles majority of support tickets
layoffs_2024                                                       1000
layoffs_2025                                                       1000
verified_source                                            NetworkWorld
month                                                      January 2026
quarter                                                         Q1 2026
region                                                    North America
layoff_size_category                                    Medium (500-2K)
stock_reaction                                                 Positive
laid_off_vs_headcount_pct                                          7.27
data_as_of                                               March 18, 2026
Name: 7, dtype: object

In [17]:
# Multiple Rows/Columns:
df.loc[0:3, ["company", "sector"]]

             company               sector
0             Amazon     E-Commerce/Cloud
1              Block              Fintech
2  Meta Reality Labs      Social Media/VR
3          Atlassian  Enterprise Software

In [21]:
# Multiple Rows/Columns:
df.loc[[3,6,8,4,24,13,16], ["company", "sector"]]

               company               sector
3            Atlassian  Enterprise Software
6             Autodesk      Design Software
8            Pinterest         Social Media
4               Oracle  Enterprise Software
24      Ergo Insurance            Insurance
13     WiseTech Global   Logistics Software
16  SK Battery America         EV Batteries

In [20]:
df.shape

(28, 26)

In [23]:
# Slicing:
df.loc[0:5, "company":"pre_layoff_headcount"]

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,pre_layoff_headcount
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,1550000
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,10000
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,79000
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,16000
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,200000
5,Salesforce,2026-01-10,1000,1.4,CRM/SaaS,USA,San Francisco,True,AI-driven efficiency and restructuring,37.9,72000

In [25]:
# Filtering:
df.loc[df["sector"]=="Fintech"]

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.0,"March 18, 2026"

# iloc

- In Pandas, iloc is a property used for integer-location based indexing, allowing you to select data from a DataFrame or Series by its numerical position rather than its label.

## Key Characteristics
- Zero-based: Indexing starts at 0 for both rows and columns.
- Exclusive Endpoints: When using slices (e.g., 0:5), the end index is excluded (returns indices 0, 1, 2, 3, and 4).
- Strict Integers: It primarily accepts integers, lists of integers, or slice objects

## Common Syntax & Usage
- The general syntax is df.iloc[row_indexer, column_indexer].

- Select a single row: df.iloc[0] retrieves the first row as a Series.
- Select a single value: df.iloc[1, 2] retrieves the value at the second row and third column.
- Slicing rows and columns: df.iloc[0:3, 1:4] selects rows 0-2 and columns 1-3.
- Selecting specific subsets: df.iloc[[0, 2], [0, 1]] selects the first and third rows for the first two columns.
- Select all rows for specific columns: df.iloc[:, [0, 2]] retrieves every row for the first and third columns

In [26]:
# Select a single row: 
df.iloc[0]

company                                                            Amazon
layoff_date                                                    2026-01-15
jobs_cut                                                            16000
pct_workforce_cut                                                     2.7
sector                                                   E-Commerce/Cloud
country                                                               USA
hq_city                                                           Seattle
ai_cited                                                            False
reason_stated                    Reduce bureaucracy and management layers
company_revenue_2025_bn                                             716.9
pre_layoff_headcount                                              1550000
stock_change_day_pct                                                  1.2
simultaneous_ai_investment_bn                                       100.0
roles_most_affected                   Middle management, program managers
replacement_roles                           AI engineers, data architects
ceo_quote                                 Moving faster with fewer layers
layoffs_2024                                                         4000
layoffs_2025                                                        14000
verified_source                                       CNBC / NetworkWorld
month                                                        January 2026
quarter                                                           Q1 2026
region                                                      North America
layoff_size_category                                           Mega (5K+)
stock_reaction                                                   Positive
laid_off_vs_headcount_pct                                            1.03
data_as_of                                                 March 18, 2026
Name: 0, dtype: object

In [ ]:
# select a single value by row and column index:
df.iloc[4, 6] # [row index, column index]

'Austin'

In [30]:
# Slicing rows and columns:
df.iloc[0:5, 0:4] # [row start:row end, column start:column end]

             company layoff_date  jobs_cut  pct_workforce_cut
0             Amazon  2026-01-15     16000                2.7
1              Block  2026-02-28      4000               40.0
2  Meta Reality Labs  2026-01-20      1500               10.0
3          Atlassian  2026-03-14      1600               10.0
4             Oracle  2026-02-01     30000               15.0

In [31]:
# Selecting specific subsets:
df.iloc[[0, 2, 4], [1, 3]] # [row indices, column indices]

  layoff_date  pct_workforce_cut
0  2026-01-15                2.7
2  2026-01-20               10.0
4  2026-02-01               15.0

In [32]:
# Select all rows for specific columns: 
df.iloc[:, [1, 3]] # [all rows, column indices]

   layoff_date  pct_workforce_cut
0   2026-01-15                2.7
1   2026-02-28               40.0
2   2026-01-20               10.0
3   2026-03-14               10.0
4   2026-02-01               15.0
5   2026-01-10                1.4
6   2026-01-25                9.0
7   2026-01-28                5.0
8   2026-02-10                4.0
9   2026-01-15               12.0
10  2026-01-20                3.4
11  2026-02-05               12.0
12  2026-01-30                7.0
13  2026-02-20               25.0
14  2026-02-15                7.0
15  2026-02-02                0.1
16  2026-03-16               37.3
17  2026-03-11                0.5
18  2026-01-15                5.0
19  2026-02-25                2.0
20  2026-02-18                2.0
21  2026-02-10               15.0
22  2026-01-22                2.0
23  2026-01-28                8.5
24  2026-03-01                2.0
25  2026-03-07               20.0
26  2026-03-13               20.0
27  2026-03-23               20.0

## difference between loc and iloc:
- The primary difference between loc and iloc in Pandas is that loc is label-based (using row/column names), while iloc is integer-position based (using 0-based indices). loc includes the last element in slices, whereas iloc excludes it. loc supports boolean indexing; iloc does not.